name = "url-shortener"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "SHORT_URLS"
id = "f45fbcc9c473454aabbdaadf8eddb5a4"
preview_id = "60ea23a8b83b400da610422f372796d2"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

#old
#kv_namespaces = [
#  { binding = "SHORT_URLS", id = "99fc264e0c1a478c99f2ba10f7961f97", preview_id = "f82a5b3e76d14d4d8f57c9c9b75956fe" }
#]